### ISSUE TITLE
net.server.close() issues

### ISSUE THREAD

**Issue by thehoglet** [sdllc/controlr#1]
Hello,

[There's a problem here](https://github.com/sdllc/controlr/blob/master/js/controlr.js#L409). [See here for the correct API usage.](https://nodejs.org/api/net.html#net_server_close_callback). Removing `this` allows the callback to be fired.

When the callback fires on a Windows 10 machine, [there's another problem here](https://github.com/sdllc/controlr/blob/master/js/controlr.js#L414). Here is the console output:

> { Error: ENOENT: no such file or directory, unlink '\.\pipe\r.76072662'
>     at Error (native)
>   errno: -4058,
>   code: 'ENOENT',
>   syscall: 'unlink',
>   path: '\\.\pipe\r.76072662' }

It's not entirely obvious from the [API notes](https://nodejs.org/api/net.html#net_server_listen_path_backlog_callback) but it looks like the pipe is removed when the server is closed (the server has already been closed by the time of the close event).

In any event, good practice would be to set `socket_file` to `NULL` just after the unlink.

Thanks for the lib! Your effort with integrating R has been very useful to me.

**Comment by duncanwerner** [comment]
Thanks for the heads up, will patch.  I probably never noticed because my use case is a single pass of create / exec / quit.  I am guessing that your use case is different -- probably multiple create / invoke / teardown steps.  Can you give me a simple example I can integrate into testing?

**Comment by thehoglet** [comment]
That's easy enough. The only code I've so far run is [your example](https://github.com/sdllc/controlr#example). I've been playing around with the package using MSVC2015 + NTVS. By having a solution that includes the vcxproj generated by GYP, it's possible to debug your javascript and C++ at the same time.

**Comment by duncanwerner** [comment]
Fixed in 02f820b7aea30ce148a5587355036dcb0bd3bc95 and npm build 2.1.3.  I had not seen NTVS, I'll have to check it out.
